#!/usr/bin/env python
# -*- coding: utf-8 -*-

table = [
	["Strength 增加力量 (str)", "str"],
	["Energy 增加精力 (eng)", "eng"],
	["Dexterity 增加敏捷 (dex)", "dex"],
	["Vitality 增加体力 (vit)", "vit"],
	["Stat Points 没用", "Unknown"],
	["Skill Points 没用", "Unknown"],
	["Life 没用", "Unknown"],
	["Max Life 增加最大生命 (life)", "life"],
	["Mana 没用", "Unknown"],
	["Max Mana 增加最大魔法 (mana)", "mana"],
	["stamina 没用", "Unknown"],
	["Max Stamina 没用", "Unknown"],
	["level 没用", "Unknown"],
	["experience 没用", "Unknown"],
	["gold 没用", "Unknown"],
	["goldbank 没用", "Unknown"],
	["Enhanced Defense % 防御增加百分比 (ed)", "ed"],
	["Enchanced Damage % 伤害增加百分比 (ed)", "ed"],
	["Enchanced Min Dmg % 增加最小伤害百分比", "Unknown"],
	["Attack Rating 增加命中率 (ar)", "Unknown"],
	["Chance of Blocking % 增加格挡率 (cob)", "cob"],
	["Min 1-handed Dmg 增加单手最小伤害", "Unknown"],
	["Max 1-handed Dmg 增加单手最大伤害", "Unknown"],
	["Min 2-handed Dmg 增加双手最小伤害", "Unknown"],
	["Max 2-handed Dmg 增加双手最大伤害", "Unknown"],
	["Damage % nv 伤害增加百分比 (隐藏)", "Unknown"],
	["Regenerate Mana % nv 法力再生", "regmana"],
	["Regenerate Mana Plus % 法力再生（隐藏） (reg)", "regmana"],
	["Heal Stemina Plus % 耐力恢复", "Unknown"],
	["lastexp 没用", "Unknown"],
	["nextexp 没用", "Unknown"],
	["Defense 增加防御", "Unknown"],
	["Def vs Missile 增加对近战的防御", "Unknown"],
	["Def vs Melee 增加对远程攻击的防御", "Unknown"],
	["Damage Reduced By 伤害减少", "dr"],
	["Magic Dmg Reduced By 魔法伤害减少", "mdr"],
	["Damage Reduced By % 伤害减少百分比 (dr)", "Unknown"],
	["Magic Resistance % 魔法抵抗百分比", "Unknown"],
	["Max Magic Resistance % 百分比增加最大魔法抵抗的百分比", "mmr"],
	["Fire Resistance % 增加火抗的百分比 (fr)", "ft"],
	["Max Fire Resistance % 增加最大火抗的百分比 (max fr)", "mfr"],
	["Lightning Resistance % 增加电抗的百分比 (lr)", "lr"],
	["Max Lightning Resistance % 增加最大电抗的百分比 (max lr)", "mlr"],
	["Cold Resistance % 增加冰抗的百分比 (cr)", "cr"],
	["Max Cold Resistance % 增加最大冰抗的百分比 (max cr)", "mcr"],
	["Poison Resistance % 增加毒抗的百分比 (pr)", "pr"],
	["Max Poison Resistance % 增加最大毒抗的百分比 (max pr)", "mpr"],
	["damageaura 没用", "Unknown"],
	["Fire Damage 增加火焰伤害", "fd"],
	["Max Fire Damage 增加火焰伤害最大值", "fmd"],
	["Lightning Damage 增加闪电伤害", "ld"],
	["Max Lightning Dmg 增加闪电伤害最大值", "mld"],
	["Magic Damage 增加魔法伤害", "Unknown"],
	["Max Magic Damage 增加魔法伤害最大值", "Unknown"],
	["Cold Damage 增加寒冷伤害", "cd"],
	["Max Cold Damage 增加寒冷伤害最大值", "mcd"],
	["Cold Length 冻结目标的时间", "Unknown"],
	["Poison Damage 增加毒伤害", "pd"],
	["Max Poison Dmg 增加毒伤害最大值", "mpd"],
	["Poison Length 目标中毒的持续时间", "Unknown"],
	["Life Stolen Per Hit Min 没用", "Unknown"],
	["Life Stolen Per Hit Max 偷取生命 (ll)", "ll"],
	["Mana Stolen Per Hit Min 没用", "Unknown"],
	["Mana Stolen Per Hit Max 偷取法力 (lm)", "lm"],
	["Stamina Drain Min 没用", "Unknown"],
	["Stamina Drain Max 没用", "Unknown"],
	["Stun Length 使目标眩晕的时间", "Unknown"],
	["RunWalk Speed % nv 跑步速率增加百分比（隐藏）", "Unknown"],
	["Attack Speed % nv 攻击速率增加百分比（隐藏）", "Unknown"],
	["other_animrate 没用", "Unknown"],
	["quantity 没用", "Unknown"],
	["value 没用", "Unknown"],
	["Durabilty 没用", "Unknown"],
	["Max Durability 增加装备耐久 (dur)", "dur"],
	["Replenish Life 自行恢复生命值 (rep)", "Unknown"],
	["Max Durability % 没用", "Unknown"],
	["Life % 增加生命上限%", "maxlife"],
	["Mana % 增加法力上限%", "maxmana"],
	["Attacker Takes Damage Of 反伤", "Unknown"],
	["Extra Gold From Monsters % 怪掉的钱增加", "eg"],
	["Chance Of Getting Magic Items % 这个就是MF", "mf"],
	["Knock Back 击退", "Unknown"],
	["Time Duration (未测试)", "Unknown"],
	["Add Class Skill 加单人技能", "add class skill"],
	["Unsentparam1 未知属性1", "Unknown"],
	["Add experience 增加百分比得到的经验值 (exp)", "exp"],
	["Heal after kill 加X生命在杀死一只怪物后 (life ek)", "life ek"],
	["Reduced prices 降低商人价格%", "Unknown"],
	["Double Herb Duration (未测试)", "Unknown"],
	["Light Radius 增加光照范围", "Unknown"],
	["Light Color nv 光照范围（隐藏）", "Unknown"],
	["Requirements % 物品对基本属性的需求 (req)", "req"],
	["Level Require 没用", "Unknown"],
	["Increased Attack Speed 提升攻击速度% (ias)", "ias"],
	["Level Require % 增加等级需求", "Unknown"],
	["Last block frame 格挡有关", "Unknown"],
	["Faster RunWalk 提升跑步速度% (frw)", "frw"],
	["Non Class skill 无职业限制技能", "non class skill"],
	["state 特殊状态,比如头上永远顶个经验祭坛", "Unknown"],
	["Faster Hit Recovery Rate 加快打击恢复 (fhr)", "fhr"],
	["Monster player count 没用", "Unknown"],
	["Poison override 没用", "Unknown"],
	["Faster Block Rate 快速格挡速度 (fbr)", "fbr"],
	["Bypass undead 没用", "Unknown"],
	["Bypass demons 没用", "Unknown"],
	["Faster Cast Rate 快速释法速度 (fcr)", "fcr"],
	["Bypass beasts 没用", "Unknown"],
	["Single Skill 增加职业限制技能", "single skill"],
	["Rest in peace 杀死怪物后恢复平静", "Unknown"],
	["Curse resistance 抗诅咒几率", "Unknown"],
	["Poison Length Reduced By % 自己的中毒时间减少 (plr)", "plr"],
	["Damage 增加伤害", "dam"],
	["Hit Causes Monster To Flee % 使怪物怪物会逃跑", "Unknown"],
	["Hit Blinds Target 打中的敌人会失明", "Unknown"],
	["Damage To Mana % 受损生命转化为提高法力", "dtm"],
	["Ignore Target Defense 无视目标防御", "itd"],
	["Target Defense % 减少目标防御%", "td"],
	["Prevent Monster Heal 防止怪物回血", "pmh"],
	["Half Freeze Duration 自己的冰冻时间减半", "hfd"],
	["Bonus To Attack Rating % 增加百分比额外的命中率", "bonus ar"],
	["Reduce Monster Defense per Hit 每次打中都减少怪物的防 御", "Unknown"],
	["Damage To Demons % 增加对恶魔系怪物的伤害", "Unknown"],
	["Damage To Undead % 增加对不死系怪物的伤害", "Unknown"],
	["Attack Rating Against Demons 增加对恶魔系怪物的命中率", "Unknown"],
	["Attack Rating Against Undead 增加最不死系怪物的命中率", "Unknown"],
	["Throwable (未测试)", "Unknown"],
	["Elemental Skill 增加火焰技能", "Unknown"],
	["All Skill Levels 增加所有技能", "skill"],
	["Attacker Takes Lightning Dmg Of 攻击者受到电伤害", "Unknown"],
	["ironmaiden_level 没用", "Unknown"],
	["lifetap_level 没用", "Unknown"],
	["thorns_percent 没用", "Unknown"],
	["bonearmor 没用", "Unknown"],
	["bonearmormax 没用", "Unknown"],
	["Attack Freezes Target 冻结目标", "freeze"],
	["Chance of Open Wounds 撕开伤口的几率 (ow)", "ow"],
	["Chance of Crushing Blow 压碎攻击的几率 (cb)", "cb"],
	["Kick Damage 增加脚踢伤害", "Unknown"],
	["Mana After Each Kill 加法力在杀死一只怪物后", "Unknown"],
	["Life After Each Demon Kill 加生命在杀死恶魔系怪物后", "Unknown"],
	["Extra Blood 没用", "Unknown"],
	["Chance of Deadly Strike 致命攻击的几率 (ds)", "ds"],
	["Fire Absorbs % 火焰吸收%", "fabs"],
	["Fire Absorbs 火焰吸收", "fabs"],
	["Lightning Absorbs % 闪电吸收%", "labs"],
	["Lightning Absorbs 闪电吸收", "labs"],
	["Magic Absorbs % 魔法吸收%", "mabs"],
	["Magic Absorbs 魔法吸收", "mabs"],
	["Cold Absorbs % 冰冷吸收%", "cabs"],
	["Cold Absorbs 冰冷吸收", "cabs"],
	["Slows Target By % 使目标减缓% (slow)", "slow"],
	["Aura 灵气赐予", "aura"],
	["Indestructible 装备无法破坏", "indestructible"],
	["Cannot be Frozen 不会被冻结", "cbf"],
	["Slower Stamina Drain % 没什么用", "Unknown"],
	["ReAnimate 杀死怪物后复活为", "Unknown"],
	["Pierce Attack % 穿透攻击", "pierce"],
	["Fire Magic Arrows or Bolts 射出魔法箭", "Unknown"],
	["Fire Explosive Arrows or Bolts 射出爆炸箭", "Unknown"],
	["Min Throw Dmg nv 增加百分比最小远程攻击", "Unknown"],
	["Max Throw Dmg nv 增加百分比最大远程攻击", "Unknown"],
	["UnCoded 未知属性", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["UnCoded", "Unknown"],
	["Attack Vs Monster 对特定怪物增加命中率", "Unknown"],
	["Damage Vs Monster 对特定怪物增加伤害", "Unknown"],
	["fade 身体透明化", "Unknown"],
	["Armor override % 没用", "Unknown"],
	["Unused183 …", "Unknown"],
	["Unused184 …", "Unknown"],
	["Unused185 …", "Unknown"],
	["Unused186 …", "Unknown"],
	["Unused187 …", "Unknown"],
	["Add Skill Tab 加入单系技能", "Unknown"],
	["Unused189 没用", "Unknown"],
	["Unused190 …", "Unknown"],
	["Unused191 …", "Unknown"],
	["Unused192 …", "Unknown"],
	["Unused193 …", "Unknown"],
	["Increased Sockets 增加凹槽（需先激活）", "Unknown"],
	["Skill On Attack 攻击时释放特定魔法", "skill on attact"],
	["Skill On Kill 杀死怪物时释放特定魔法", "skill on kill"],
	["Skill On Death 自己死亡时放特定魔法", "skill on death"],
	["Skill On Hit 打中时释放特定魔法", "skill on hit"],
	["Skill On Levelup 升级时释放特定魔法", "skill on levelup"],
	["Unused200 没用", "Unknown"],
	["Skill On Get Hit 被打中时释放特定魔法", "Unknown"],
	["Unused202 没用", "Unknown"],
	["Unused203 …", "Unknown"],
	["Charged Skill 特定聚气技能", "Unknown"],
	["Unused205 没用…", "Unknown"],
	["Unused206 …", "Unknown"],
	["Unused207 …", "Unknown"],
	["Unused208 …", "Unknown"],
	["Unused209 …", "Unknown"],
	["Unused210 …", "Unknown"],
	["Unused211 …", "Unknown"],
	["Unused212 …", "Unknown"],
	["Unused213 …", "Unknown"],
	["Defense (on Lvl) 按等级增加防御", "Unknown"],
	["Enhanced Defense (on Lvl) 按等级提高防御", "Unknown"],
	["Life (on Lvl) 按等级提高生命值", "Unknown"],
	["Mana (on Lvl) 按等级提高魔法值", "Unknown"],
	["Maximum Damage (on Lvl) 按等级提高最大伤害", "Unknown"],
	["Enhanced MaxDmg (on Lvl) 按等级提高最大伤害%", "Unknown"],
	["Strength (on Lvl) 按等级增加力量", "Unknown"],
	["Dexterity (on Lvl) 按等级增加敏捷", "Unknown"],
	["Energy (on Lvl) 按等级增加精力", "Unknown"],
	["Vitality (on Lvl) 按等级增加体力", "Unknown"],
	["Att Rating (on Lvl) 按等级增加命中率", "Unknown"],
	["Bonus to Att Rating % (on Lvl) 按等级提高额外的命中率", "Unknown"],
	["Maximum Cold Dmg (on Lvl) 按等级增加最大寒冷伤害", "Unknown"],
	["Maximum Fire Dmg (on Lvl) 按等级增加最大火伤害", "Unknown"],
	["Maximum Lightning Dmg (on Lvl) 按等级增加最大闪电伤害", "Unknown"],
	["Maximum Poison Dmg (on Lvl) 按等级增加最大毒伤害", "Unknown"],
	["Cold Resistance % (on Lvl) 按等级增加百分比冰抗", "Unknown"],
	["Fire Resistance % (on Lvl) 按等级增加百分比火抗", "Unknown"],
	["Lightning Resistance % (on Lvl) 按等级增加百分比电抗", "Unknown"],
	["Poison Resistance % (on Lvl) 按等级增加百分比毒抗", "Unknown"],
	["Absorbs Cold Damage (on Lvl) 按等级提高吸收寒冷伤害能力", "Unknown"],
	["Absorbs Fire Damage (on Lvl) ……吸收火伤害能力", "Unknown"],
	["Absorbs Lightning Damage (on Lvl) ……吸收闪电伤害能力", "Unknown"],
	["Absorbs Poison (per lvl) 很诱惑的属性,不过没用", "Unknown"],
	["Attacker Takes Damage of (on Lvl) 按等级反伤", "Unknown"],
	["Extra Gold From Monsters % (on Lvl)按等级提高怪掉的钱", "Unknown"],
	["Chance of Getting Magic Items % (on Lvl) 按等级提高MF几率", "Unknown"],
	["Heal Stamina Plus % (on Lvl) 没用", "Unknown"],
	["Maximum Stamina (on Lvl) 没用", "Unknown"],
	["Damage to Demons % (on Lvl) 没用", "Unknown"],
	["Damage to Undead % (on Lvl) 没用", "Unknown"],
	["Att Rating against Demons (on Lvl) 没用", "Unknown"],
	["Att Rating against Undead (on Lvl) 没用", "Unknown"],
	["Chance of Crushing Blow (on Lvl) 按等级提高压碎攻击的几率", "Unknown"],
	["Chance of Open Wounds (on Lvl) ……提高撕开伤口的几率", "Unknown"],
	["Kick Damage (on Lvl) 按等级提高踢伤害", "Unknown"],
	["Chance of Deadly Strike (on Lvl) 按等级提高致命攻击几率", "Unknown"],
	["Find Gems per level 没用", "Unknown"],
	["Repair 1 Durability In Seconds 按时间恢复耐久", "rep dur"],
	["Replenish 1 Quantity In Seconds 回复数量", "rep quantity"],
	["Increased Stack Size 增加数量", "stack"],
	["UnCoded 没用", "Unknown"],
	["UnCoded …", "Unknown"],
	["UnCoded …", "Unknown"],
	["UnCoded …", "Unknown"],
	["UnCoded …", "Unknown"],
	["UnCoded …", "Unknown"],
	["UnCoded ..", "Unknown"],
	["UnCoded …", "Unknown"],
	["UnCoded .", "Unknown"],
	["UnCoded ..", "Unknown"],
	["UnCoded .", "Unknown"],
	["UnCoded .", "Unknown"],
	["UnCoded .", "Unknown"],
	["Defense (by Time) [1] 以下为属性时间", "Unknown"],
	["Defense (by Time) [2]", "Unknown"],
	["Life (by Time)", "Unknown"],
	["Mana (by Time)", "Unknown"],
	["Max Damage (by Time) [1]", "Unknown"],
	["Max Damage (by Time) [2]", "Unknown"],
	["Strength (by Time)", "Unknown"],
	["Dexterity (by Time)", "Unknown"],
	["Energy (by Time)", "Unknown"],
	["Vitality (by Time)", "Unknown"],
	["Attack Rating (by Time) [1]", "Unknown"],
	["Attack Rating (by Time) [2]", "Unknown"],
	["Max Cold Dmg (by Time)", "Unknown"],
	["Max Fire Dmg (by Time)", "Unknown"],
	["Max Lightning Dmg (by Time)", "Unknown"],
	["Max Poison Dmg (by Time)", "Unknown"],
	["Cold Resistance % (by Time)", "Unknown"],
	["Fire Resistance % (by Time)", "Unknown"],
	["Lightning Resistance % (by Time)", "Unknown"],
	["Poison Resistance % (by Time)", "Unknown"],
	["Absorbs Cold Damage (by Time)", "Unknown"],
	["Absorbs Fire Damage (by Time)", "Unknown"],
	["Absorbs Lightning Damage (by Time)", "Unknown"],
	["Blessed Aim", "Unknown"],
	["Gold From Monsters % (by Time)", "Unknown"],
	["Find Magic Items % (by Time)", "Unknown"],
	["Heal Stamina Plus % (by Time)", "Unknown"],
	["Max Stamina (by Time)", "Unknown"],
	["Damage vs Demon % (by Time)", "Unknown"],
	["Damage vs Undead % (by Time)", "Unknown"],
	["Attack Rating vs Demon (by Time)", "Unknown"],
	["Attack Rating vs Undead (by Time)", "Unknown"],
	["Chance of Crushing Blow (by Time)", "Unknown"],
	["Chance of Open Wounds (by Time)", "Unknown"],
	["Kick Damage (by Time)", "Unknown"],
	["Chance of Deadly Strike (by Time)", "Unknown"],
	["item_find_gems_bytime 没用", "Unknown"],
	["item_pierce_cold 减少敌人对冰技能抵抗%", "Unknown"],
	["item_pierce_fire 减少敌人对火技能抵抗%", "Unknown"],
	["item_pierce_ltng ……对闪电技能抵抗%", "Unknown"],
	["item_pierce_pois ……对毒素技能的抵抗%", "Unknown"],
	["item_damage_vs_monster 没用", "Unknown"],
	["item_damage_percent_vs_monster …", "Unknown"],
	["item_tohit_vs_monster …", "Unknown"],
	["item_tohit_percent_vs_monster …", "Unknown"],
	["item_ac_vs_monster …", "Unknown"],
	["item_ac_percent_vs_monster …", "Unknown"],
	["firelength …", "Unknown"],
	["burningmin …", "Unknown"],
	["burningmax …", "Unknown"],
	["progressive_damage …", "Unknown"],
	["progressive_steal ..", "Unknown"],
	["progressive_other ..", "Unknown"],
	["progressive_fire …", "Unknown"],
	["progressive_cold …", "Unknown"],
	["progressive_lightning …", "Unknown"],
	["item_extra_charges …", "Unknown"],
	["progressive_tohit …", "Unknown"],
	["poison_count …", "Unknown"],
	["damage_framerate …", "Unknown"],
	["pierce_idx …", "Unknown"],
	["passive_fire_mastery 增加百分比火技能伤害", "fmaster"],
	["passive_ltng_mastery ……闪电技能伤害", "lmaster"],
	["passive_cold_mastery ……寒冷技能伤害", "cmaster"],
	["passive_pois_mastery 百分比转为毒素伤害", "pmaster"],
	["passive_fire_pierce 减敌人对火技能抗性（测试效果为增加元素伤害上限）", "fp"],
	["passive_ltng_pierce ……对闪电技能抗性", "lp"],
	["passive_cold_pierce ……对寒冷技能抗性", "cp"],
	["passive_pois_pierce ……对毒素技能抗性", "pp"],
	["passive_critical_strike 不清楚", "Unknown"],
	["passive_dodge 三闪之一", "dodge"],
	["passive_avoid 三闪之一", "avoid"],
	["passive_evade 三闪之一", "evade"],
	["passive_warmth 热情", "Unknown"],
	["passive_mastery_melee_th 未测试", "Unknown"],
	["passive_mastery_melee_dmg …", "Unknown"],
	["passive_mastery_melee_crit …", "Unknown"],
	["passive_mastery_throw_th …", "Unknown"],
	["passive_mastery_throw_dmg …", "Unknown"],
	["passive_mastery_throw_crit …", "Unknown"],
	["passive_weaponblock …", "Unknown"],
	["passive_summon_resist …", "Unknown"],
	["modifierlist_skill 没用", "Unknown"],
	["modifierlist_level 没用", "Unknown"],
	["last_sent_hp_pct 没用", "Unknown"],
	["source_unit_type 没用", "Unknown"],
	["source_unit_id 没用", "Unknown"],
	["shortparami 未测试", "Unknown"],
	["questitemdifficulty 未测试", "Unknown"],
	["passive_mag_mastery 未测试", "Unknown"],
	["passive_mag_pierce 未测试", "Unknown"],
]


from sfm.string_match import choose_best
from macro.bot import bot

def find_index(text):
    index_table = dict()
    choice = list()
    for index, (attribute_name, label) in enumerate(table):
        index_table[label] = index
#         choice.append(attribute_name)
        choice.append(label)
        
    matched = choose_best(text, choice)
    index = index_table[matched]
    return index

def move_to_property(label):
    index = find_index(label)
    bot.delay(1.0)
    x, y = bot.get_position()
    bot.left_click(x, y, index)

x, y = bot.get_position()
for i in range(24):
	bot.left_click(x, y, n=1, pre_dl=0.2)
    
if __name__ == "__main__":
	pass
#     index = find_index("fcr")
	label = "life ek"
	move_to_property(label)
	